# install Software

winget.exe install Notepad++.Notepad++
winget.exe install NexusMods.Vortex
winget.exe install 7zip.7zip
winget.exe install Cisco.CiscoWebexMeetings
winget.exe install Audacity.Audacity
winget.exe install BlueMicrophones.BlueSherpa
winget.exe install BraveSoftware.BraveBrowser
winget.exe install TGRMNSoftware.BulkRenameUtility
winget.exe install Piriform.CCleaner
winget.exe install Discord.Discord
winget.exe install Docker.DockerDesktop
winget.exe install HandBrake.HandBrake
winget.exe install HeidiSQL.HeidiSQL
winget.exe install CodecGuide.K-LiteCodecPack.Full
winget.exe install Logitech.LGS
winget.exe install VentisMedia.MediaMonkey
winget.exe install Microsoft.EdgeWebView2Runtime
winget.exe install Microsoft.WindowsTerminal
winget.exe install Notepad++.Notepad++
winget.exe install RaspberryPiFoundation.RaspberryPiImager
winget.exe install Meltytech.Shotcut
winget.exe install TeamViewer.TeamViewer
winget.exe install UnityTechnologies.Unity.2020
winget.exe install VideoLAN.VLC
winget.exe install WinDirStat.WinDirStat
winget.exe install Balena.Etcher
winget.exe install Heroku.HerokuCLI
winget.exe install SlackTechnologies.Slack
winget.exe install WinSCP.WinSCP
winget.exe install Microsoft.VC++2013Redist-x64
winget.exe install Corsair.iCUE.3
winget.exe install Microsoft.VC++2008Redist-x86
winget.exe install Microsoft.VC++2015-2019Redist-x86
winget.exe install Microsoft.XNARedist
winget.exe install PrivateInternetAccess.PrivateInternetAcc…
winget.exe install Malwarebytes.Malwarebytes
winget.exe install PuTTY.PuTTY
winget.exe install EpicGames.EpicGamesLauncher
winget.exe install OpenShot.OpenShot
winget.exe install Cisco.WebexTeams
winget.exe install IcecreamApps.PDFCandy
winget.exe install Oracle.VirtualBox
winget.exe install Microsoft.WindowsPCHealthCheck
winget.exe install Nvidia.GeForceExperience
winget.exe install Nvidia.PhysX
winget.exe install Microsoft.UpdateAssistant
winget.exe install Microsoft.VisualStudioCode
winget.exe install UnityTechnologies.UnityHub
winget.exe install Microsoft.PowerToys
